import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.EventQueue;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import java.awt.Font;
import java.awt.GridLayout;
import javax.swing.JComboBox;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import com.toedter.calendar.JCalendar;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.beans.PropertyChangeListener;
import java.util.Calendar;
import java.beans.PropertyChangeEvent;

import javax.swing.Timer;

public class CountdownFrame extends JFrame {

	/**
	 * Class fields
	 */
	//serialVersionUID - included so Eclipse doesn't rant at me. 
	private static final long serialVersionUID = -713919736046162562L;
	private JPanel contentPane; //the pane with content
	private Timer countTimer; //timer to trigger the countdown.
	private String selectedFormat; //the string representing the selected format
	private Calendar target; //the target date
	private long millisecCount; //the difference between the present moment and the target date
	private JCalendar calendar;	//the calendar control on the application
	private JLabel lblCount; //displays the countdown

	/**
	 * Launch the application.
	 */
	public static void main(String[] args) {
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					CountdownFrame frame = new CountdownFrame();
					frame.setVisible(true);
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
	}

	/**
	 * Create the frame.
	 */
	public CountdownFrame() {
		
		//most of the code below is autogenerated from WindowBuilder
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setBounds(100, 100, 450, 300);
		contentPane = new JPanel();
		contentPane.setBorder(new EmptyBorder(5, 5, 5, 5));
		contentPane.setLayout(new BorderLayout(0, 0));
		setContentPane(contentPane);
		
		//to give the countdown millisecond accuracy, a timer action is fired
		//every 1 millisecond
		countTimer = new Timer(1, new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				Calendar now = Calendar.getInstance();
				millisecCount = Math.abs(target.getTimeInMillis() - now.getTimeInMillis());
				updateUI();
			}
		});
		
		//defaults to preferred format - ddd hh:mm:ss.msc
		lblCount = new JLabel("000 00:00:00.000");
		lblCount.setFont(new Font("Arial Black", Font.PLAIN, 36));
		lblCount.setOpaque(true);
		lblCount.setBackground(Color.WHITE);
		lblCount.setBorder(BorderFactory.createLoweredBevelBorder());
		lblCount.setHorizontalAlignment(SwingConstants.CENTER);
		contentPane.add(lblCount, BorderLayout.NORTH);
		
		calendar = new JCalendar();
		calendar.addPropertyChangeListener(new PropertyChangeListener() {
			public void propertyChange(PropertyChangeEvent arg0) {
				countTimer.stop();
				target = calendar.getCalendar();
				//set the target date's "time" to 12:00:00 AM/00:00:00 on
				//the given date
				//else, the countdown would set to the time at which the calendar's
				//value was altered every time.
				target.set(Calendar.HOUR, 0);
				target.set(Calendar.HOUR_OF_DAY, 0);
				target.set(Calendar.MINUTE, 0);
				target.set(Calendar.SECOND, 0);
				target.set(Calendar.MILLISECOND, 0);
				countTimer.start();
			}
		});
		//default to Christmas of the current year.
		calendar.getDayChooser().setDay(25);
		calendar.getMonthChooser().setMonth(11);
		contentPane.add(calendar, BorderLayout.SOUTH);
		//set the target to midnight on default date.
		target = calendar.getCalendar();
		target.set(Calendar.HOUR, 0);
		target.set(Calendar.HOUR_OF_DAY, 0);
		target.set(Calendar.MINUTE, 0);
		target.set(Calendar.SECOND, 0);
		target.set(Calendar.MILLISECOND, 0);
		JPanel formatPanel = new JPanel();
		contentPane.add(formatPanel, BorderLayout.CENTER);
		formatPanel.setLayout(new GridLayout(1, 0, 0, 0));
		
		JLabel lbl1 = new JLabel("Selected Format:");
		formatPanel.add(lbl1);
		lbl1.setFont(new Font("Arial", Font.PLAIN, 18));
		
		//parameterizing the ComboBoxModel so Eclipse won't warn me about it.
		JComboBox<String> comboFormats = new JComboBox<String>();
		comboFormats.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent arg0) {
				selectedFormat = (String)comboFormats.getSelectedItem();
			}
		});
		comboFormats.setFont(new Font("Arial", Font.ITALIC, 18));
		comboFormats.setModel(new DefaultComboBoxModel<String>(new String[] {"ddd hh:mm:ss.msc", "yy/mm/dd hh:mm:ss", "mmm/dd hh:mm:ss", "www/dd hh:mm:ss", "hhhh:mm:ss.msc", "mmmmmm:ss.msc", "ssssssssss", "milliseconds"}));
		comboFormats.setSelectedIndex(0);
		formatPanel.add(comboFormats);
		countTimer.start(); //start the timer once everything has been loaded.
	}
	
	public void updateUI() {
		//get current moment
		Calendar now = Calendar.getInstance();
		
		if (now.compareTo(target) < 0) { //we are still counting down
			lblCount.setForeground(new Color(0, 128, 255)); //shade of blue if counting down to target
			this.setTitle("How Long Will It Be?"); //update frame title to reflect countdown
		}
		else { //we are on the date/after the date has passed.
			lblCount.setForeground(new Color(204, 0, 0)); //shade of red if counting up from target
			this.setTitle("How Long Has It Been?"); //update frame title to reflect counting up
		}
		lblCount.setText(getLabelString()); //all this does is fetch the appropriate label
		//on update
	}
	
	private String getLabelString() {
		//variable to hold our values
		String retVal;

		if (selectedFormat.equals("yy/mm/dd hh:mm:ss")) { //show a count for years, months, days, hours, minutes, seconds (no msc)
			long ss = millisecCount / 1000 % 60;
			long mm = millisecCount / 1000 / 60 % 60;
			long hh = millisecCount / 1000 / 60 / 60 % 24;
			long dd = millisecCount / 1000 / 60 / 60 / 24 % 30;
			long mo = millisecCount / 1000 / 60 / 60 / 24 / 30 % 12;
			long yy = millisecCount / 1000 / 60 / 60 / 24 / 30 / 12;
			
			//update the return variable to the appropriate thing
			retVal = String.format("%02d/%02d/%02d %02d:%02d:%02d", yy, mo, dd, hh, mm, ss);
		}
		else if (selectedFormat.equals("mmm/dd hh:mm:ss")) { //months, days, hours, mins, secs
			//most of the calcuations are the same for each; just
			//different fields
			long ss = millisecCount / 1000 % 60;
			long mm = millisecCount / 1000 / 60 % 60;
			long hh = millisecCount / 1000 / 60 / 60 % 24;
			long dd = millisecCount / 1000 / 60 / 60 / 24 % 30;
			long mmm = millisecCount / 1000 / 60 / 60 / 24 / 30;
			
			retVal = String.format("%03d/%02d %02d:%02d:%02d", mmm, dd, hh, mm, ss);
		}
		else if (selectedFormat.equals("www/dd hh:mm:ss")) { //weeks, days, hours, mins, secs
			long ss = millisecCount / 1000 % 60;
			long mm = millisecCount / 1000 / 60 % 60;
			long hh = millisecCount / 1000 / 60 / 60 % 24;
			long dd = millisecCount / 1000 / 60 / 60 / 24 % 7;
			long www = millisecCount / 1000 / 60 / 60 / 24 / 7;
			
			retVal = String.format("%03d/%02d %02d:%02d:%02d", www, dd, hh, mm, ss);
			
		}
		else if (selectedFormat.equals("hhhh:mm:ss.msc")) { //hours, mins, secs, millisecs
			long msc = millisecCount % 1000;
			long ss = millisecCount / 1000 % 60;
			long mm = millisecCount / 1000 / 60 % 60;
			long hhhh = millisecCount / 1000 / 60 / 60;
			
			retVal = String.format("%04d:%02d:%02d:%03d", hhhh, mm, ss, msc);
		}
		else if (selectedFormat.equals("mmmmmm:ss.msc")) { //mins, secs, millisecs
			long msc = millisecCount % 1000;
			long ss = millisecCount / 1000 % 60;
			long mmmm = millisecCount / 1000 / 60;
			
			retVal = String.format("%06d:%02d.%03d", mmmm, ss, msc);
		}
		else if (selectedFormat.equals("ssssssssss")) { //seconds only
			long sssss = millisecCount / 1000;
			retVal = String.format("%010d", sssss);
		}
		else if (selectedFormat.equals("milliseconds")) { //milliseconds only
			retVal = Long.toString(millisecCount);
		}
		else { //default: days, hours, minutes, seconds, milliseconds			
			long msc = millisecCount % 1000;
			long ss = millisecCount / 1000 % 60;
			long mm = millisecCount / 1000 / 60 % 60;
			long hh = millisecCount / 1000 / 60 / 60 % 24;
			long ddd = millisecCount / 1000 / 60 / 60 / 24;
			
			retVal = String.format("%03d %02d:%02d:%02d.%03d", ddd, hh, mm, ss, msc);
		}
		
		//return the string, appropriately formatted
		return retVal;
	}

}
